### ISSUE TITLE
Package up as a proper library

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#1]
We should add a `.cabal` file, switch to depending on existing libraries rather than re-defining standard classes, and so on.

The module interface needs some thought. I'd be inclined to go for something like
 * `Optics`: main module that re-exports the most useful bits from other modules
 * `Optics.{Lens,Traversal,...}`: tag definition and functions for working with each different flavour of optic
 * `Optics.Internal`: the newtype and other key things that live inside the abstraction barrier

**Comment by kosmikus** [comment]
You want to use top-level `Optics` rather than `Data.Optics` or `Data.Optic`? I'm ok with that. Does it really make sense to have different modules for each kind of optic?

**Comment by adamgundry** [comment]
I've never really understood why we need a `Data.` (or `Control.`, etc.) prefix on every hierarchical module name, but perhaps there's a good reason I'm missing? I don't feel very strongly about it.

I think one-module-per-optic is useful for documentation purposes, so we can set out the functions typically used with a particular flavour, even if most users actually import the main module.

**Comment by adamgundry** [comment]
Resolved by #8 and #9.
