### ISSUE TITLE
Merge Optics.<flavor> and Optic.<flavor>.Internal

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#101]
I think there is no good reason for having the split, all pretty much all non-internal flavor specific modules do is just reexport stuff.

If any flavor needs things that are actually internal (and usable by other internal modules), we can have them for these.

**Comment by adamgundry** [comment]
Presumably we would keep the `Optics.<flavour>` modules, as we want them for documentation purposes, and drop the internal ones unless needed?

I'm not sure there is any great harm to the current arrangement.

**Comment by arybczak** [comment]
> Presumably we would keep the Optics.<flavour> modules, as we want them for documentation purposes, and drop the internal ones unless needed?

> I'm not sure there is any great harm to the current arrangement.

Well, it's a bit confusing where to add a new function to and when you add something you need to re-export it in the other module for it to be visible, which I find tiring when I try things out.
