### ISSUE TITLE
Add functional update operators?

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#104]
For example:
```hs
(+~) :: (Num a, Is k A_Setter) => Optic k i s t a a -> a -> s -> t
o +~ n = over o (+ n)
infixr 4 +~
```
How do people feel about these? I've used them more often than the state-based ones.

**Comment by arybczak** [comment]
Yeah, I wonder about these. All of these are pretty much `o %~ op n` for some `op`. Is writing `%~ (+ n)` or `%~ (/ n)` instead too annoying?

**Comment by arybczak** [comment]
I think we should keep the operators we have and only add additional ones if they cannot be trivially expressed in terms of existing ones. Otherwise we might end up as the `lens` library ;)

Let's close for now, feel free to reopen if you disagree.
