### ISSUE TITLE
Flavour-polymorphic conversions to van Laarhoven representation?

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#105]
Could we generalise `lensVL` and `toLensVL` so that they work for arbitrary optic flavours, e.g. as `vl` and `toVL`? This might make interoperation with `lens` code less noisy, but it's not clear if we can get enough type inference.

**Comment by arybczak** [comment]
We can potentially stick `toVL` into a type class, but it won't work for `vl`, the constraints will be ambiguous.

Is that actually a problem though? For traversals `(ix)traversalVL` and `(i)traverseOf` are inverses, whereas for folds `(ix)foldVL` and `(i)traverseOf_`, so I think it's fine for these. Lens is the only type where `toLensVL` is a bit awkward (perhaps `asLensVL` would be a better name).

**Comment by phadej** [comment]
For prisms story isn't as nice.

**Comment by arybczak** [comment]
This can be observed by looking at `Language.Haskell.TH.Optics`. Lenses and traversals required porting and for recursive data types you need to convert between Optic and VL encoding as when you are inside VL lens/traversal you can't use Optic encoding. But Prisms didn't require any porting, code just compiled as-is.

**Comment by arybczak** [comment]
Same story for `Optics.Internal.PrismTH`, the only modification needed for that module was replacing (.) with (%) for composition, whereas `Optics.Internal.FieldTH` required complete overhaul to how lenses/traversals were generated.

**Comment by arybczak** [comment]
We have prismVL internally [here](https://github.com/well-typed/optics/blob/24bbdab004a3d021439f722b02002ceb33802864/generic-optics/src/Optics/Generic/Internal/Utils.hs), but yes, having them in the public API would be a bit complicated wrt. profunctors dependency and doesn't buy us much, considering how they are constructed/modified in lens.

**Comment by adamgundry** [comment]
Well if my code makes use of a van Laarhoven prism provided by some library, but I want to use `optics`, it would be nice to have the conversion available. Seems like another candidate for an `Optics.Compat` module?

**Comment by arybczak** [comment]
Hmm, right, that makes sense. It makes transition more appealing as even if some pieces were missing, VL equivalents could be wrapped with these.

We'd need to rename `foldVL` from `Optics.Fold` though because it doesn't take a VL fold, it takes VL traversal (we don't need Contravariant constraint, because we can use Bicontravariant once we're inside the Optic constructor). I'm not sure what would be a good replacement though. `mkFold` is an obvious one, though maybe there are better options.

**Comment by arybczak** [comment]
Request for VL wrappers for `Iso` and `Prism` split as #165. Let's close this one.
