### ISSUE TITLE
Add Grate optic?

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#107]
Closed profunctor gives rise to a Grate optic: https://r6research.livejournal.com/28050.html

It looks like it sits below Review and it generalizes `zipWith`. We could include it for completeness.

**Comment by phadej** [comment]
`Grate` is useful only with `Distributive` / `Representable` functors.
It **doesn't** generalise `zipWith` for lists neither for maps (`intersectionWith`).

I'm neutral about `Grate` inclusion. `IxGrate` may be interesting.

**Comment by arybczak** [comment]
Let's close this one for now.
