### ISSUE TITLE
TH generation of lenses usable as labels (without Generics)

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#131]
Funnily enough, if you have

```haskell
data T1
  = T11 { tint :: Int, tchar :: Char }
  | T12 { tint :: Int, tchar :: Char, _tname :: String }
  deriving (Show)

instance {-# OVERLAPPING #-} HasField' "tint" T1 Int where
  field' = lens tint (\t n -> t { tint = n })

instance {-# OVERLAPPING #-} HasField' "tchar" T1 Char where
  field' = lens tchar (\t c -> t { tchar = c })
```

then you can use `#tint` and `#tchar` with `T1` as it'll just pick these instances instead of trying to generate lenses with Generics. We should add TH support for this.

**Comment by arybczak** [comment]
I implemented basic generation of HasField instances via TH and checked how compile times compare with Generics.

Generating lenses for `data T = T1 {...} | T2 {..}` where each constructor has 50 fields with the same names with Generics takes 14 seconds and consumes a bit over 1.4GB of memory, doing the same with TH needs 3 seconds and a bit over 300MB (with GHC flags set to -A32m -j4)

I think we don't want to merge #121 in its current form, they're too expensive (and potentially hard to maintain). Instead I'm going to just pull bare HasField/HasConstructor classes (maybe HasPosition, I'm not sure yet) and add TH code for generation of instances for them. This will be similar to `makeClassy`/`makeFields` except then you won't need to pre-create all your Has* classes or put all data types in one module, so it'll kinda subsume this functionality (we can mark it as deprecated then).

In the end we'll have support for overloaded labels, but via TH, not Generics.

**Comment by adamgundry** [comment]
Hmm, it's unfortunate that Generics is so much slower than TH here. I guess it isn't altogether surprising, though. Is it really so terrible to support both? That is, provide an overlappable instance that uses generics, but have the option of invoking TH to generate the overlapping instances.

Regarding your comments in https://github.com/well-typed/optics/pull/132/files#diff-746b0e6cd69862927408a8081136f72bR167 about the limitations imposed by the functional dependencies, I agree with your analysis. This is something I ran into as well with the ORF work. Fundamentally I think it is to be expected that higher-rank fields are not usable with any solution to field name overloading based on constraint solving: bidirectional type inference necessarily depends on higher-rank types being known immediately, before any constraint solving takes place. I guess something similar applies to existentials.

The problem with phantom type parameters or those under type families feels less fundamental, but I'm not aware of a way to solve it. The key issue is that `s` and `t` are not really free to vary independently; rather they should be the same type constructor applied to different parameters. Thus `name s b -> t` is actually too strong.

**Comment by arybczak** [comment]
> Is it really so terrible to support both? That is, provide an overlappable instance that uses generics, but have the option of invoking TH to generate the overlapping instances.

Unfortunately there are multiple problems with this.
- since we really want to have base support for labels in optics-core, we'd need to port the appropriate generic-lens code and put it there. That's another (very complicated) piece of code to watch for. I honestly have very faint idea how this code works.
- Overlappable instance that uses Generics can produce unexpected error messages for people who want to use TH or write instances by hand.
- Using overlappable instance actually makes overall project compilation times even worse, because I think then GHC will generate code for an optic once per file in which it's used, as opposed to once per project (if you have explicit instance declarations).

I just don't think it's worth it especially since compilation times I got with experimentation above clearly say that these are pretty much unusable in anything other than a (small) toy project.

Regarding higher rank fields, I actually experimented a little yesterday and lifted that restriction, albeit at a cost.

So the LabelOptic type class looked like this:

```haskell
class LabelOptic (name :: Symbol) k s t a b | name s -> k
                                            , name t -> k a
                                            , name s b -> t b
                                            , name t a -> s where
  labelOptic :: Optic k NoIx s t a b
```

here's some test data:

```haskell
data Pet = Cat | Dog | Fish deriving Show
data Human = Human { humanPets :: [Pet] } deriving Show

peter :: Human
peter = Human [Cat, Dog]
```

and I had instances that looked like this:

```haskell
instance LabelOptic "pets" A_Lens Human Human [Pet] [Pet] where
  labelOptic = lensVL $ \f s -> (\v -> s { humanPets = v }) <$> f (humanPets s)
```

But it turns out that with instances written like this GHC is not able to match on the appropriate instance in rather fundamental cases:

```haskell
λ> set #pets [] peter

<interactive>:7:1: error:
    • No instance for (LabelOptic "pets" A_Lens Human () [Pet] [a0])
        arising from a use of ‘it’
    • In the first argument of ‘print’, namely ‘it’
      In a stmt of an interactive GHCi command: print it
```

What helps is writing the instance like this instead:
```
instance (a ~ [Pet], b ~ [Pet]) => LabelOptic "pets" A_Lens Human Human a b where
  labelOptic = lensVL $ \f s -> (\v -> s { humanPets = v }) <$> f (humanPets s)
```

Then it works fine because GHC is able to match the instance:
```haskell
λ> set #pets [] peter
Human {humanPets = []}
```

But I noticed that if do you that, the you can weaken the fundeps to:
```haskell
class LabelOptic (name :: Symbol) k s t a b | name s -> k
                                            , name t -> k
                                            , name s b -> t
                                            , name t a -> s where
  labelOptic :: Optic k NoIx s t a b
```

And then fields of rank 2 types (and as you mentioned, reviews for constructors with existential types inside) can be defined just fine.

The downside is that this essentially pushes functional dependencies to "per-instance" basis as opposed to being class wide. So If `s` or `t` is known, then you recover `s -> a` and `t -> b`, but if you're working with unsolved LabelOptic constraint, you don't and in non-trivial cases you need to sprinkle some type annotations:

For example:
```
type HasConfig k s = (LabelOptic' "config" k s Config, Is k A_Getter)

doStuff :: (MonadReader r m, HasConfig k r) => m ()
doStuff = do
  (_::Config) <- asks (view #config)
  -- ...
  pure ()
```
Here we need to annotate the result type, otherwise GHC complains about ambiguous type variable. Now this is a bit contrived example since when you use LabelOptic' like this, you'll use the field you just pulled and will not need the type annotation, but here's something else:

```
randomValue
  :: forall s m r
  .  (MonadState s m, LabelOptic' "rng" A_Lens s R.StdGen, R.Random r)
  => m r
randomValue = do
  (r, g) <- gets $ view (rng % to R.random)
  modify' $ set rng g
  pure r
  where
    rng :: Lens' s R.StdGen
    rng = #rng
```

Here you need to annotate the `rng`, because you're composing it with R.random from System.Random which is polymorphic in an input.

I'm not sure how much of a problem this would be in practice (as I feel like you will usually use overloaded labels either with concrete types or in cases like `doStuff` when it's not a big deal to annotate the result.

@adamgundry any thoughts about this approach? I like it's a sensible tradeoff that shouldn't be much of a problem in practice, but perhaps I didn't think of appropriate example.

**Comment by arybczak** [comment]
In theory generic-optics can provide orphan overlappable instance of `LabelOptic`, although that doesn't sound very robust.

**Comment by arybczak** [comment]
One more note:

When working with unsolved LabelOptic constraints a lot, inference can be recovered by providing a helper class:

```haskell
class HasConfig s where
  config :: Lens' s Config
instance (LabelOptic' "config" k s Config, Is k A_Lens) => HasConfig s where
  config = toLens #config
```

and using `config` instead of `#config`, then ambiguous result type will be no longer an issue. And, unlike `lens` approach with `makeFields` or `makeClassy`, `HasConfig` is completely independent from the code that defines `LabelOptic "config"` instances.

**Comment by arybczak** [comment]
Note for a future reader: disregard last 3 posts - giving up these fundeps is too expensive in terms of added confusion in presence of unsolved LabelOptic constraints, so they stay. We'll have to live without labels for fields of rank 2 types and reviews for existential types.

In practice this shouldn't be much of a problem, second case is trivial as `unto <constructor>` gives you the review, first case is solvable with analogous `to <field-selector>`. There is a potential problem with field name clashes, though I wager that name clashes for rank 2 type fields are somewhat rare.
