### ISSUE TITLE
OverloadedLabels requires either manually writing instances or using TemplateHaskell

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#140]
I really like `generic-lens` base approach. It was using existing library, and was so convenient.

The inconvinience is visible from the example

https://github.com/well-typed/optics/blob/f5c678166546c333e850579558fe9f9b7133c6c7/optics-core/src/Optics/Internal/Optic.hs#L191-L231

if optics wouldn't be scary topic to begin with!

**Comment by arybczak** [comment]
See https://github.com/well-typed/optics/issues/131#issuecomment-464494920, generic-lens is not usable at the moment.

**Comment by adamgundry** [comment]
We're not planning to address this for the initial release, but in the future we could conceivably adopt either `generic-optics` or the proposed magical `HasField` class, so leaving this open.

**Comment by adamgundry** [comment]
See kcsongor/generic-lens#108 for current thinking on this.
