### ISSUE TITLE
Make diagrams a bit bigger, add indexed affine fold/traversal

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#143]
Also add README (or explanation in some other form) how to use it in order to regenerate images, because I have no idea.

@phadej

**Comment by phadej** [comment]
`make diagrams` to regenerate

**Comment by phadej** [comment]
Bigger as in zoomed or more space between vertices in the graph?

**Comment by arybczak** [comment]
I think spacing is fine (though ideally there would be more space between edges and vertices in  https://github.com/well-typed/optics/blob/e9c33d1a202388c8ffa8646432a75881ffba86eb/optics/reoptics.png), but diagrams in bigger resolution would be nice.

**Comment by arybczak** [comment]
Also, https://github.com/well-typed/optics/blob/e9c33d1a202388c8ffa8646432a75881ffba86eb/optics/indexedoptics.png for some reason has a lot of empty space at the bottom. Can we get rid of it?

**Comment by arybczak** [comment]
Done via #144.
