### ISSUE TITLE
Move matching and isn't to AffineTraversal?

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#148]
Is there any reason not to define `matching` and `isn't` on affine traversals rather than prisms? That would allow them to be used on the composition of a lens and a prism, which is nice.

I came across this while working on #145, and am tempted to include it in that to save an unnecessary conflict.

**Comment by arybczak** [comment]
We can make `matching` work on affine folds. I'm not sure about `isn't`, its name suggests it works for constructors.

**Comment by phadej** [comment]
@arybczak one can have

```haskell
*Optics> isn't (_Left  % _Left) (Left (Right 'x'))
True
```

So I don't know why we couldn't have

```haskell
*Optics> isn't (_Left  % _1 % _Left) (Left (Right 'x'))
True
```

OTOH, we do have

```haskell
*Optics> :t hasn't 
hasn't :: Is k A_Fold => Optic' k is s a -> s -> Bool
```

too.

**Comment by arybczak** [comment]
That makes sense, you've convinced me ;) I think having them acting on affine folds would be fine.
