### ISSUE TITLE
So we need `Equality`

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#151]
If we remove that, then `Optic` will always be morally coercible in `s t a b`.
I didn't ever used `Equality`, `simple` could be an `Iso` too.

```haskell
newtype Optic (k :: *) (is :: [*]) s t a b =
  Optic { getOptic :: forall p j. Profunctor p => Optic_ k p j (Curry is j) s t a b }
```

which will make all optics `CoercibleOptics`. And `Ixed`, if/when `conjoined'` is moved to our `Profunctor`

**Comment by arybczak** [comment]
Yeah, I was wondering about that too.

I didn't use `simple`, though I found `equality` useful as it's the optic equivalent of identity function. As there is no reason for `equality` not to be an Iso, I also don't really see the reason for having Equality.
