### ISSUE TITLE
Split optics-th into two packages?

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#159]
See https://github.com/ekmett/lens/issues/844 for background. We should probably aim to release with GHC 8.8 support.

**Comment by arybczak** [comment]
I saw that ticket and thought "well, we got this handled as we have optics-th", so I'm not sure what is the advantage of splitting it further.

**Comment by phadej** [comment]
IMHO, the `Language.Haskell.TH.Optics` module is not-so-useful. I'd remove it and let `optics-th` to be the only "Derive optics with TH"

Now that package has two responsibilities, and sooner or later there will be tentions

**Comment by arybczak** [comment]
Code for TH generation of optics makes use of `Language.Haskell.TH.Optics` and it makes a lot of things easy, so it's definitely useful.

**Comment by phadej** [comment]
It uses maybe dozen of things from a huge API of that module.
