### ISSUE TITLE
Authors/maintainers in .cabal files

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#167]
I don't think the maintainer email address `optics@well-typed.com` exists yet (unless @kosmikus has set it up). We should either set it up or change it. @arybczak do you have an opinion on what this should be?

For the authors lists, I'm not sure about including the original authors of code we have ported, at least without asking first. We should certainly credit them appropriately in the description/README, but listing as an author could be taken to imply more support for `optics` than we can necessarily assume...

Are there any other `.cabal` metadata fields that need attention?

**Comment by arybczak** [comment]
> @arybczak do you have an opinion on what this should be?

optics@well-typed.com seems good to me. I'm using my well-typed.com email address for repositories from Well-Typed LLP organization, so feel free to include me in there. In any case I think almost all communication will be done via github at this point.

> listing as an author could be taken to imply more support for optics than we can necessarily assume...

Hmm, perhaps. That idea didn't cross my mind, so asking if they're fine with it sounds like a good idea :+1:
