### ISSUE TITLE
LensyReview and PrismaticGetter

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#169]
From https://github.com/well-typed/optics/pull/153#issuecomment-489461017:

> Regarding `LensyReview` and `PrismaticGetter`, I was meaning to start a separate discussion on what we should do with them. I think they are something of a misnomer (and misleadingly documented at present, probably by me): a `LensyReview` is really a "backwards `Lens`" just as a `Review` is a "backwards `Getter`". If we're going to keep them, we should be more explicit and have canonical introduction/elimination rules for them. But I'm not totally convinced that we shouldn't just drop them and limit `re` to `Getter`/`Review`/`Iso`.

Thinking about this a bit further, it would be odd from a subtyping perspective if `re` didn't work on a `Lens` but did on an `Iso`. So I suppose our options are to properly document and add canonical forms for `LensyReview`/`PrismaticGetter`, or to have `re` of a `Lens` return a `Review`. I'm slightly inclined to the first, but what do others think?

If we do keep them, I'd suggest more explicit names, perhaps `ReversedLens` and `ReversedPrism`? (Just as `Review` could be `ReversedGetter`, not that I'm suggesting renaming it.)

**Comment by arybczak** [comment]
I like `PrismaticGetter`, `LensyReview` is a bit meh.

`Reversed` is alright, but perhaps an abbreviation would be better - `ReLens`/`RePrism`? Or maybe `Coprism` and `Colens` in correspondence to profunctor classes?

**Comment by adamgundry** [comment]
On an aesthetic level I also like `Prismatic` and dislike `Lensy`.

Isn't the dual of a `Lens` a `Prism`? That makes me disinclined to use `Co` as a prefix. I'm happy with `Re` though, and having `re` turn a `Lens` into a `ReLens` makes a certain sense.

**Comment by arybczak** [comment]
> Isn't the dual of a Lens a Prism?

To be fair I'm not sure. The `Co` prefix comes from constraints used to construct these optic kinds (`Strong` for `Lens`, `Costrong` for `LensyReview`, `Choice` for `Prism`, `Cochoice` for `PrismaticGetter`).

Maybe there are two kinds of duality here, my CT knowledge is very shallow.

**Comment by adamgundry** [comment]
Reopening as I'm still minded to rename to `ReLens` and `RePrism`. The docs are better now though.

**Comment by adamgundry** [comment]
@arybczak we should make a final decision about the names here.

**Comment by adamgundry** [comment]
We're planning to go for `ReversedLens` and `ReversedPrism`.
