### ISSUE TITLE
Minor naming suggestions

### ISSUE THREAD

**Issue by Gabriel439** [well-typed/optics#17]
I would like to suggest the following renames:

* Strip the `A_` prefix from the optic tags (i.e. `A_Lens` → `Lens`)
* Rename `Is` to `IsA`
* Rename `Optic` to `A`

Then a constraint would read like:

```haskell
Lens `IsA` Getter
```

.... and an optic type would read like:

```haskell
A Lens (a, b) a
```

... which would no longer require a type synonym

I don't feel very strongly about this, so feel free to reject this suggestion if you disagree :)

**Comment by arybczak** [comment]
IMO it's quite neat, the problem is with things that start with An, i.e. An_Equality, An_Iso etc.

**Comment by adamgundry** [comment]
Interesting. I suppose we could have `type An = A` and then people could at least get the grammar right when writing type signatures. :wink:

I'm a bit concerned that this might be confusing when the optic flavour is a type variable, e.g. in optic-polymorphic operations such as composition, or in type errors. For example:
```hs
(%) :: (k `IsA` m, l `IsA` m, m ~ Join k l) => A k s t u v -> A l u v a b -> A m s t a b
```

**Comment by kosmikus** [comment]
Are we still considering this?

**Comment by arybczak** [comment]
I don't think we do, there are a few drawbacks to the proposal:

1. `A_` convention for tags generates nicer error messages, e.g. `A_Setter cannot be composed with A_Getter`
2. The problem of A vs An
3. As Adam pointed out, functions polymorphic in the optic flavor have awkward type signatures

In theory (2) and (3) can be alleviated by introducing type synonyms, but this creates confusion.

 I'm going to close, please reopen if needed.
