### ISSUE TITLE
mkFold vs foldVL

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#179]
Split from #165.

`mkFold` used to be called `foldVL`, but I changed it as it takes something more general than VL fold since `f` doesn't need to be `Contravariant`.

But it occurs to me now that we can't have proper `foldVL` because we use `wander` for folds internally and it doesn't know about `Contravariant`.

Shall we rename it back? I'd be inclined to do so. @adamgundry what do you think?

**Comment by adamgundry** [comment]
As a point of comparison, we have `atraversalVL` and `toAtraversalVL` for `AffineTraversal`, even though our definition of `AffineTraversalVL` is slightly wrong as it takes the "`Pointed` dictionary" as an explicit argument. So there's precedent for deviating slightly here. As long as we document the infelicity I'd be happy with `foldVL`.
