### ISSUE TITLE
Alternatives for % as optic composition (and its fixity)

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#20]
The main problem is that it conflicts with Data.Ratio. Did you consider any alternatives?

**Comment by kosmikus** [comment]
I think we're quite happy to discuss other options, if you have any suggestions.

**Comment by arybczak** [comment]
Also, see a reddit comment of Edward I dug up: https://www.reddit.com/r/haskell/comments/13l9vj/getting_started_with_lenses/c75w6ap/

> Until lens 3.4 this was a consistent application of the above principle, applying a function `(%) :: a -> (a -> b) -> b`.
>
> So knowing one led you to the other. In 3.4 we switched to `(&)` after complaints, because it was causing issues with traditional Haskell golf code that involved `Data.Ratio` on lambdabot.

**Comment by phadej** [comment]
I was accidentally looking into "what to use as a composition combinator" (for one different, opaque encoding of optics), and I was thinking about `%` (single character) and `.>` too.

I guess we can have `.>` as the default. Only practical use can show how annoying (or not) is to not have single character combinator.

**Comment by adamgundry** [comment]
Sounds like `.>` is the way to go.

**Comment by kosmikus** [comment]
I'm ok with `.>` as well.

**Comment by phadej** [comment]
thinking a bit more: `o .> o'` (`lens`) is `icompose (\i j -> j) (o % o')` (current `optics`)

Also we could/should have indexedgetter, indexedaffinetraversal etc; so I think that indexed vs. non indexed is another dimension of optics lattice; not really a part of it. (every non-indexed thing is indexed thing with a trivial index)

Let's not change the operator just yet.

**Comment by arybczak** [comment]
> thinking a bit more: `o .> o'` (`lens`) is `icompose (\i j -> j) (o % o')` (current `optics`)

Yeah, but that is just a consequence of how indexed optics behave in lens, i.e. only leftmost index is preserved by default.

> Also we could/should have indexedgetter, indexedaffinetraversal etc; so I think that indexed vs. non indexed is another dimension of optics lattice; not really a part of it. (every non-indexed thing is indexed thing with a trivial index)

I'm not sure about this one. Anything above traversal/fold gives you zero or one result, what is the point of indexing it?

**Comment by phadej** [comment]
> I'm not sure about this one. Anything above traversal/fold in the hierarchy gives you zero or one result, what is the point of indexing it?

It gives you single item, but you don't know the index beforehand. For example one can write `ixLT k` affinetraversal for map (better version of [`lookupLT`](http://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Map-Lazy.html#v:lookupLT)), which will also give you the key (which is less than given `k`).

It's one thing to be able write everything using optics, and in fact `updateWithKeyLT` doesn't even exist in `containers` (but could).

**Comment by arybczak** [comment]
Perhaps we can have `.>` as a replacement for `%` and `<.>` variant for composition of two indexed optics that automatically flattens indices with `(,)`?

Then we can remove `icompose{2,3,4,5}` and have `icomposeN` become `icompose` (that flattens arbitrary number of indices using chosen function).

**Comment by adamgundry** [comment]
I think it makes sense to offer `<%>`, `<%` and `%>` (under some names) as they are a bit more comprehensible than `ioverMulti` (even if we have the latter too). On the naming front, the asymmetry of `.>` vs `<.>` makes me prefer the `%` options, despite the clash with `Data.Ratio`.

Unless we could come up with something else? Perhaps something like `.|` instead of `%`?

**Comment by kosmikus** [comment]
I'm personally also leaning towards keeping `%`. I'm surprised the conflict with `Data.Ratio` is such a big deal, because I would almost always use `/` rather than `%` in practice. But on the other hand, if this conflict was bad enough to remove a `%` operator in `lens`, then perhaps we should be careful as well.

Other two-character options involving dot yet still allowing putting angle brackets on both sides might be `.-` or `-.`.

**Comment by arybczak** [comment]
I'm reluctant about keeping `%` because it's proven to be problematic in lens - see https://github.com/well-typed/optics/issues/20#issuecomment-441403441.

On the other hand, lens has `<.` only because of limitations of regular composition of indexed and regular, non index preserving optic:

```
λ> :t iover (imapped . _1)

<interactive>:1:8: error:
    • Couldn't match type ‘Indexed i a (Identity b)’
                     with ‘a0 -> Identity b0’
      Expected type: AnIndexedSetter i (f a1) (f b1) a b
        Actual type: (a0 -> Identity b0) -> f a1 -> Identity (f b1)
    • In the first argument of ‘iover’, namely ‘(imapped . _1)’
      In the expression: iover (imapped . _1)
```
but
```
λ> :t iover (imapped <. _1)
iover (imapped <. _1)
  :: (FunctorWithIndex i f, Field1 s b1 a b2) =>
     (i -> a -> b2) -> f s -> f b1
```

We don't really need that variation because optics compose just fine with regular composition operator.

`.>` in lens is just an alias for `.`, because when composition order is reversed, it works fine:

```
λ> :t iover (_1 . imapped)
iover (_1 . imapped)
  :: (Field1 s t (f a) (f b), FunctorWithIndex i f) =>
     (i -> a -> b) -> s -> t
```

Also note that `.>` in lens has a somewhat confusing quirk that's described in the docs:

> f . g (and f .> g) gives you the index of g unless g is index-preserving, like a Prism, Iso or Equality, in which case it'll pass through the index of f.

And surely:

```
λ> :t iover (imapped .> curried)
iover (imapped .> curried)
  :: FunctorWithIndex i f1 =>
     (i -> (a -> b -> c) -> d -> e -> f2)
     -> f1 ((a, b) -> c) -> f1 ((d, e) -> f2)
```

Here `.>` preserves the index of `imapped` even though it looks like it shouldn't, but that's because `curried` is index preserving.

But that's exactly what we deal with in `optics` as here all of optics are either indexed or index preserving, so if `%` becomes `.>`, it'll actually match the behavior of `lens` in this regard, the only difference being that when two indexed optics are preserved, then both indices are retained.

> I'm personally also leaning towards keeping `%`. I'm surprised the conflict with `Data.Ratio` is such a big deal, because I would almost always use `/` rather than `%` in practice. But on the other hand, if this conflict was bad enough to remove a `%` operator in `lens`, then perhaps we should be careful as well.
> 
> Other two-character options involving dot yet still allowing putting angle brackets on both sides might be `.-` or `-.`.
There is quite a lot of these already defined: http://hayoo.fh-wedel.de/?query=.-

http://hayoo.fh-wedel.de/?query=.%3E is not defined in nearly as many packages.

**Comment by phadej** [comment]
I'm not sure code golfing in lambdabot counts. I checked, in my last project there was a single use of `%` from Ratio.

I'm not against having `.>`, but I learned to like `%`.

Also:

```haskell
λ Control.Lens> :t imapped .> imapped
imapped .> imapped
  :: (Settable f1, FunctorWithIndex i1 f2, FunctorWithIndex i2 f3,
      Indexable i2 p) =>
     p a (f1 b) -> f2 (f3 a) -> f1 (f2 (f3 b))
```

we don't match `lens`: `optics` preserves both indices

```haskell
λ *Optics> :t imapped % imapped
imapped % imapped
  :: (FunctorWithIndex i1 f1, FunctorWithIndex i2 f2) =>
     Optic A_Setter '[i1, i2] (f1 (f2 a)) (f1 (f2 b)) a b
```

**Comment by phadej** [comment]
One undirectional (and IMO pretty) variant is `//`; yet it clashes with intersections (`Data.List`, `Data.Vector`); but those have names and usually imported qualified

**Comment by arybczak** [comment]
> I'm not sure code golfing in lambdabot counts

Well, I guess it does enough that they made an effort to change the API because of it.

**Comment by phadej** [comment]
So we have options (including new ones):

1. `%` and
2. `.>` are debated a lot
3. `//` clashes with `Data.List.//`
4. `#` means something else in `lens` but otherwise is unused in the ecosystem

I think `.>` is the worst of these four.

**Comment by arybczak** [comment]
`#` is also fine. We already have it as an infix version of `review` in `Optics.Operators`, but I'm not really attached to it.

**Comment by kosmikus** [comment]
I could probably get used to `#`.

**Comment by adamgundry** [comment]
I'm not sure I see much benefit of `#` over `%`. The fact that `lens` uses it for something else would make migrating code more troublesome.

**Comment by arybczak** [comment]
It looks like `%` is about to stay (for the lack of better alternative at least).

While we're at it we can discuss its fixity. All of the `.>`, `<.` and `<.>` in lens have `infixr 9`, but that's pretty much because `(.)` is also `infixr 9`.

To me `infixl 9` would be more natural (@phadej also agrees, see https://github.com/well-typed/optics/pull/106#discussion_r250809200), but I guess there is also compatibility argument.

What do you think?

**Comment by kosmikus** [comment]
Can you explain to me where `infixl` vs `infixr` for `%` itself would make a difference? Optics composition is supposed to be associative, so does it have an effect for efficiency? Or are we only talking about the other operator variants? But still, could you provide examples?

**Comment by arybczak** [comment]
There is no difference in performance, the difference is mostly in error messages of having to wrap things in parentheses sometimes.

E.g. there was `hmap (coerce (rep % sop %)) (go sList)` in optics-sop. With `infixr` it has to be `npPrisms = hmap (coerce ((rep % sop) %)) (go sList)`. With `infixl` you'd need parentheses in the symmetric case, i.e. if operator section would be for precomposition.

Also you get somewhat different error messages. E.g. with `infixr 9`:

```
λ> :t folded <%> ifolded % ifolded

<interactive>:1:1: error:
    • Indexed optic is expected
        (in the first argument of ‘(<%>)’)
    • In the expression: folded <%> ifolded % ifolded

<interactive>:1:1: error:
    • Use (<%>) or icompose to combine indices of type ‘j’ and ‘i0’
        (in the second argument of ‘(<%>)’)
    • In the expression: folded <%> ifolded % ifolded
```

but with `infixl 9'`:
```
λ> :t folded <%> ifolded % ifolded

<interactive>:1:1: error:
    • Indexed optic is expected
        (in the first argument of ‘(<%>)’)
    • In the first argument of ‘(%)’, namely ‘folded <%> ifolded’
      In the expression: folded <%> ifolded % ifolded
```

Having `infixl` I think is more natural to how optics are written, i.e. from left to right. Chains of function composition are usually written in the opposite direction (at least that's how I write them) so `infixr` works there.

**Comment by phadej** [comment]
one argument is the type of `ifolded <%> ifolded <%> ifolded`. Should the index be `((i,j),k)` or `(i, (j, k))`?

**Comment by arybczak** [comment]
Composition operators were made `infixl` in #163. As for the other stuff discussed, current state of affairs wrt. symbols for operators seems to be the best we can think of at the moment.

**Comment by codygman** [comment]
Late to the party, but very glad `.>` wasn't chosen. I would have been happy with `#` as well even though it's overloaded. I think the UX could be hugely affected by having to compose with 2 characters over 1 here too.

**Comment by adamgundry** [comment]
I think the fact that `#` is already used for overloaded labels (amongst other things) makes it rather less appealing, because we'd end up with `#foo # #bar` instead of the marginally better `#foo % #bar`. Using `%` isn't beautiful, but it seems to work out okay in practice.
