### ISSUE TITLE
Rename Ix* type synonyms to Indexed*

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#208]
For compatibility with lens.

**Comment by arybczak** [comment]
I'd be inclined to actually skip this, as I tried it and the result doesn't satisfy me, because:
1) `Ix` prefix looks neat and is consistent with `NoIx`, `WithIx` and `noIx`.
2) `IxAffineTraversal` is fine, `IndexedAffineTraversal` is imo too long.
3) The "incompatibility with lens" issue when converting can be solved by simple search-and-replace and given that indexed optics aren't very prevalent, it's not like there will be a lot of these to replace.
4) Because the API can be easily extended to include coindexed optics, if it does happen (I'm pretty sure it will at some point), there will be additional type synonyms and both indexed/conindexed optics. Now, `IndexedCoindexedAffineTraversal` sounds terrible whereas `IxCoixAffineTraversal` is pretty ok.

Given the above, I'd skip this issue, merge outstanding PRs and release the damn thing already ;) @adamgundry any objections?

**Comment by adamgundry** [comment]
No objections to skipping the renaming, so I'll close this. It wouldn't be hard to add more verbose type synonyms later (or for someone else to do it in their own code) if using identical names to `lens` is actually helpful.

Let's discuss the release on #130.
