### ISSUE TITLE
Depending on base vs indexed optics

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#21]
For indexed optics to be useful we need a bunch of `Functor/Foldable/TraversableWithIndex` instances for commonly used containers. However, that will incur dependency on `containers`, `unordered-containers` and `vector` (possibly `bytestring` and `text`). Is there a satisfactory solution to that problem?

All I can think of is providing these instances (and other stuff that requires `mtl` or `transformers`) in package named e.g. `optics-extra` as orphan instances, but that's probably a bad idea.

**Comment by arybczak** [comment]
I think it's reasonable to depend on things that ship with GHC and which newer `Cabal` depends on, so `array`, `bytestring`, `containers`, `text`, `transformers`, `mtl`, `template-haskell` and `text`.

**Comment by adamgundry** [comment]
Yes, this is a problem. My inclination would be to have a main `optics` package that provides lots of common instances and incurs lots of dependencies, but then keep `optics-core` minimal. This means that users concerned about dependency footprint can use `optics-core` (albeit without much support for indexed optics in particular), and there is at least a canonical place for the orphans. Probably `optics` would then pull in `optics-sop` as well.

See also ekmett/lens#647 for a similar discussion regarding `lens`.

**Comment by adamgundry** [comment]
Another option that came up in discussion yesterday: perhaps the `Functor/Foldable/TraversableWithIndex` classes themselves don't need to be in `optics-core` at all?

**Comment by arybczak** [comment]
I think this is solved, i.e. we have optics-core that depends on `base`, `array` and `containers` with indexed optics and missing instances for vector/hashmap supplied by optics-extra.
