### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#22]
* [ ] The Haddock comments for `Optic` should explain the new indices introduced in #19.
* [ ] We should explain how subtyping works and include the nice diagram from https://github.com/well-typed/optics/pull/19#issuecomment-444278219.
* [ ] The Haddocks could do with a general review, e.g. the documentation for the main `Optics` module is a bit unstructured.
* [ ] We should document the library's divergences from `lens` (see https://github.com/well-typed/optics/pull/19#issuecomment-438279907 and later).
* [ ] We should explain the philosophy behind the library (perhaps in a README, see #5).

**Comment by phadej** [comment]
![profunctor-optics](https://user-images.githubusercontent.com/51087/50853410-cbf8b700-138a-11e9-8098-5f6077e0f15e.png)

A variant of the diagram with `Traveral1` and `Fold1` .
- red arrows are "can be converted with `re`"
- all other arrows are `Is`.
- there are no indexed optics, but I argue that the blue-green box  + `Setter` has an indexed copy (i.e. `IxLens`, `IxTraversal1`, ..., `IxSetter`). Maybe some of these kinds aren't practical; but I don't see any reason not to include them for completeness.

**Comment by arybczak** [comment]
What is the difference between green and blue arrow? I'd like to have indexed variants ideally as well.

**Comment by arybczak** [comment]
It's also `PrismaticGetter`, not `PrismyGetter`, although I guess that can be up to discussion

**Comment by phadej** [comment]
It's possible to add indexed optics to the diagram I just merged, as we don't yet have `Fold1` and `Traversal1`. But even then, the diagram becomes messy. I think adding `IndexedLens` .. is good for completeness (and might make easier to explain what these indexed optics are about: instead of one "result" you get a pair)

**Comment by arybczak** [comment]
Then perhaps we can stay with the version I provided in #19? It also doesn't require as much overhead as yours as it's graphviz.

**Comment by adamgundry** [comment]
Perhaps there's something to be said for multiple diagrams, in the interests of clarity? We don't necessarily need to have all the information in one complex image. We might ideally want to separate:
 * The core hierarchy, without indexed optics or `re`
 * A diagram of what `re` does, including `PrismaticGetter` and `LensyReview`
 * A diagram explaining indexed optics

**Comment by phadej** [comment]
@adamgundry good point about multiple diagrams.

@arybczak I like graphviz when i don't know the structure. But for this case I'd like to have precise control over the layout, to highligh important parts
- Iso, Prism, Lens, Affine - diamond
- Lens, Affine, Traveral1, Traversal - diamond
- The above diamond has "Getter shadow"

This structure is lost if you let graphviz do the layout.

**Comment by kosmikus** [comment]
Some remarks regarding the diagrams:

- I also would like multiple diagrams. In particular, having some kind of "simple" diagram only covering lenses, prisms, traversals, isos, equality (essentially the subset covered by the "profunctor optics" paper) would be helpful.

- I prefer the layouted versions.

- Please explain the different kinds of arrows. A sentence like "all other arrows are `Is`" really makes me wonder why you have different arrows at all.

Other remarks on documentation:

I'm currently missing some documentation basics, but it's possible I'm overlooking them. Some points I'd like mentioned somewhere central:

- An explanation of all type arguments of the `Optic` type.

- An explanation of how synonyms like `Lens` map to the `Optic` type.

- An explanation of how optic constructors always target a concrete type of optics, but optic destructors are always overloaded by means of the `Is` class.

**Comment by phadej** [comment]
For the reference: 
![screenshot from 2019-01-14 14-40-06](https://user-images.githubusercontent.com/51087/51113330-579a9980-180a-11e9-8f23-41f730ce59e1.png)

Adapter = Iso

Our diagram do have similar diamond,: the join of a Lens and a Prism is an AffineTraversal, not Traversal. So our diagram is more granular, and it's tricky to make it resemble something published (it seems, someone actually found my blog post about affine traversals a best reference to cite).

**Comment by kosmikus** [comment]
Oh, I'm not necessarily thinking that our diagram has to match something published. I merely think (but could be wrong) that in terms of popularity of concepts Lenses, Traversals and Prisms are the the most widely known (in this order). And I suspect nearly everyone feels comfortable with Isos or equalities, even though they aren't necessarily thought of as optics.

**Comment by kosmikus** [comment]
Some more thoughts about the diagram:

- Can we flip the vertical axis of the diagram, please? In general, join is `⋁`, and intended to be the least "upper" bound of its arguments. Having join move down is counter-intuitive imho.

- The documentation currently claims that we're dealing with a join-semilattice. I don't see that this is the case. It looks like "just" a partially ordered set to me.

**Comment by phadej** [comment]
> The documentation currently claims that we're dealing with a join-semilattice. I don't see that this is the case. It looks like "just" a partially ordered set to me.

True, there aren't all *joins*; but still most. I don't know which is better: "lattice-like" or "poset / partial ordered set"

**Comment by phadej** [comment]
I merged most in flight PRs and made haddocks: http://oleg.fi/haddocks/optics-core-20190115/Optics.html (diagrams are flipped, doctests pass, but no big changes except for indexed optics which is WIP)

**Comment by adamgundry** [comment]
I'm making some progress on this in #145.

**Comment by adamgundry** [comment]
This is now essentially done, with some further improvements in #172.
