### ISSUE TITLE
Extra Symbol argument to Is for better errors?

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#233]
```
19:24 < kosmikus> I wonder if "Is" or some variant of it should take an additional Symbol argument.
19:25 < kosmikus> which would repeat the name of the function introducing the constraint.
19:25 < kosmikus> then we could mention that in the error message too.
```

**Comment by adamgundry** [comment]
I've been experimenting with this on branch `233-isfor`, and it seems that
```hs
class Is k l => IsFor (s :: Symbol) k l
```
works, although it will require fairly extensive changes to make use of it.

We can use the trick from https://www.well-typed.com/blog/2015/07/checked-exceptions/ to coerce explicitly between `IsFor` dictionaries with different symbols, although this is a bit of a pain because of https://gitlab.haskell.org/ghc/ghc/issues/17167.

I'm increasingly inclined to think that this should be solved in GHC itself, so I've raised https://gitlab.haskell.org/ghc/ghc/issues/17168.

**Comment by arybczak** [comment]
I did a similar thing with `HasSingleIndex`, but later removed the Symbol field because it doesn't work in all cases, it looks messy and when you change the definition name or move code around you need to remember to update the symbol.

I'd leave it, as you say it should be done in GHC.

**Comment by adamgundry** [comment]
Okay, let's leave it.
