### ISSUE TITLE
Is there an equivalent to 'non' from lens?

### ISSUE THREAD

**Issue by chris-martin** [well-typed/optics#238]
Thanks for this library, I'm really excited about it! I'm just starting to explore and tentatively see if I can convert some of my `lens`-using code to `optics`.

There's one place where I use [non](https://hackage.haskell.org/package/lens-4.17.1/docs/Control-Lens-Iso.html#v:non) with a `Map`, just like the examples in the lens documentation. I'm not finding any corresponding `Iso` in optics. I imagine it would look something like this:

```haskell
non :: Eq a => a -> Iso' (Maybe a) a
non z = iso f g
  where
    g x | x == z     =  Nothing
        | otherwise  =  Just x

    f Nothing   =  z
    f (Just x)  =  x
```

Was this an intentional omission because `non` (as noted in the lens docs) is not a true isomorphism? Is there another way to achieve the same effect with optics?

**Comment by arybczak** [comment]
> Was this an intentional omission because non (as noted in the lens docs) is not a true isomorphism?

Nope, I don't think there is a reason not to include it. Do you have any experience with usefulness of `non'` and `anon`? It's probably reasonable to include all three.

**Comment by adamgundry** [comment]
Thanks for the feedback. I agree, and in general we are open to adding more combinators from `lens` where they are commonly useful, we just haven't ported all of them.

> Was this an intentional omission because `non` (as noted in the lens docs) is not a true isomorphism?

My position is that such not-quite-law-abiding constructions are fine provided the preconditions for them being valid are clearly documented, which seems to be the case for `non`. We shouldn't expect types to rule out all possible errors, rather we should strive for a good balance between functionality and safety.

**Comment by chris-martin** [comment]
> Do you have any experience with usefulness of `non'` and `anon`?

I do not, I'm afraid I haven't yet wrapped my head around them.

> [...] provided the preconditions for them being valid are clearly documented [...] we should strive for a good balance between functionality and safety

Yes, that sounds very agreeable.
