### ISSUE TITLE
Should Ixed really require the traversal to be affine?

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#243]
@phadej pointed out that requiring `Ixed` to be an affine traversal rules out structures like multimaps, where an index may hit multiple values. Should we weaken it to produce a traversal?

EDIT: another possibility is to have the optic kind depend on the type, using a fundep or another type family.

**Comment by arybczak** [comment]
> Should we weaken it to produce a traversal?

I don't think it's a good idea, especially since there are no instances atm that benefit from that.

Fundep sounds alright, though it'll complicate things a bit. What about a separate type class?

**Comment by arybczak** [comment]
Fixed by #262.
