### ISSUE TITLE
Export Curry/CurryCompose or hide icomposeN?

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#245]
The inferred type of `icomposeN` exposes internals:
```hs
*Optics> :t icomposeN
icomposeN
  :: (Optics.Internal.Optic.TypeLevel.CurryCompose is,
      NonEmptyIndices is) =>
     Optics.Internal.Optic.TypeLevel.Curry is i
     -> Optic k is s t a b -> Optic k (WithIx i) s t a b
```
I think we should either export these from `Optics`, or perhaps not expose `icomposeN`...

**Comment by arybczak** [comment]
> I think we should either export these from Optics

Sounds good to me :+1:
