### ISSUE TITLE
Too broad dependency ranges on subpackages

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#249]
I noticed recently that `optics.cabal` defines these dependencies:
```
               , optics-core            >= 0.1       && <1
               , optics-extra           >= 0.1       && <1
               , optics-th              >= 0.1       && <1
```
The upper bounds seem much too loose, given that `optics` reexports whole modules from these packages. This means that even a minor version bump to a subpackage could change the API exported by `optics-0.1`.

I think the right thing to do is to specify bounds as `== 0.1.0.*`. Or am I missing something?

**Comment by arybczak** [comment]
Restricting bounds sounds good to me, I also noticed that they seem unnecessarily wide.
