### ISSUE TITLE
Improve haddocks of template-haskell-optics

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#252]
In other words, port https://github.com/ekmett/lens/pull/856.

**Comment by patrickt** [comment]
Taking a look at this today: it looks like, unlike the TH splices in `lens`, there aren’t any type signatures that are ifdef-ed such that they differ between `template-haskell` versions. If y’all would prefer, I can go back and test/add necessary ifdefs with old versions of `template-haskell`: thoughts? Alternatively, I can just annotate the optics themselves that are version-dependent.

**Comment by patrickt** [comment]
Looks like we have to go back to 7.10 or earlier to get API breakage re. this module’s type signatures—but the project in toto doesn’t build on 7.10 due to base constraints on `indexed-profunctors`. So the best thing to do here seems to annotate just the optics that are version-dependent.

**Comment by arybczak** [comment]
Indeed, supporting only GHC 8.x allowed for a lot of CPP simplifications.
