### ISSUE TITLE
view for Iso

### ISSUE THREAD

**Issue by ilyakooo0** [well-typed/optics#263]
```haskell
view :: Iso s t a b -> s -> a
```

This seems to be false.

The actual definition of `view` is:

```haskell
Is k A_Getter => Optic' k is s a -> s -> a
```

which in our case is essentially:

```haskell
Is k A_Getter => Iso' s a -> s -> a
```

... which is pretty sad...

**Comment by arybczak** [comment]
?

**Comment by ilyakooo0** [comment]
I'm just pointing out that strictly speaking I can not `view` an iso of type `Iso String Bool Int Double`, but the docs seem to say that I can.

**Comment by arybczak** [comment]
See `Optics.ReadOnly` module, `getting` does what you want.

**Comment by ilyakooo0** [comment]
Thanks!

The docs for `Iso` are still slightly misleading.

**Comment by arybczak** [comment]
Can you point to a problematic documentation piece?

**Comment by ilyakooo0** [comment]
https://github.com/well-typed/optics/blob/6c28f6f223e484be98a369308f8a53e2b4dd114c/optics-core/src/Optics/Iso.hs#L24

This should probably be `Iso' s a -> s -> a `
