### ISSUE TITLE
More instances for indexed optics.

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#28]
There's a todo in the code.

I think we should depend at least on `containers`.

**Comment by kosmikus** [comment]
The plan is to keep dependencies on `optics-core` as minimal as possible (although depending on libraries shipped with GHC should in principle be ok). Everything else should go into a different package, ideally, but it can of course still be part of the overall project.

**Comment by adamgundry** [comment]
Right, see #21. In the interests of making progress, I think we can start by just adding boot library deps to `optics-core` directly, pending further rearrangement.

**Comment by phadej** [comment]
Resolved in #33
