### ISSUE TITLE
Add Bitraversable Traversals

### ISSUE THREAD

**Issue by cfraz89** [well-typed/optics#288]
Porting from lens, have noticed the lack of Bitraversable optics, namely `both`.

Would be nice to add `both` and `both1` to optics or optics-extra.
`both` can be defined as:

```
both :: Bitraversable r => Traversal (r a a) (r b b) a b
both = traversalVL $ \f -> bitraverse f f
```

**Comment by arybczak** [comment]
That requires dropping support for GHC 8.0.2.

See https://github.com/well-typed/optics/issues/96 for more details.

**Comment by adamgundry** [comment]
I previously argued for keeping 8.0.2 support, but I think enough time has gone by that we could reasonably drop it.

That said, @cfraz89 does `each` or `chosen` work in your use case? I'm not sure how often people use `both` at types other than `(,)` or `Either`.

**Comment by hasufell** [comment]
I think 8.0.2 is something that still exists reasonably in projects that have a hard time upgrading their tool chain stack. Supporting it sounds worthwhile, but shouldn't it be possible to have features that at least require ghc 8.2? I don't see a problem with that.

**Comment by cfraz89** [comment]
@adamgundry Yes we were just using it on `(,)`, `each` is fine here.
