### ISSUE TITLE
Introduce Field1/... and Swapped classes

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#29]
Note: it would be nice to have

```haskell
_1 :: Iso i (Identity a) (Identity b) a b
_1 :: Lens i (a, c) (b, c) a b
...
```

it's a small thing, but I think it should be easy to do with `optics` (`lens` would require `QuantifiedConstraints`).

**Comment by arybczak** [comment]
Field* is in #33, although it's straightforward port from `lens` for now so it doesn't give you `Iso` for `Identity`...
