### ISSUE TITLE
optics-0.3 release

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#297]
I think due GHC-8.10 it's good to make a release. We have few breaking changes along the way, is there something we would like to get in?

I timebox this for two weeks, until Wed 2019-04-09, after which we should try to cut the release.

The #290 generics optics experiment should either be merged or postponed to the later release. (I have no opinion).

cc @arybczak @adamgundry

**Comment by arybczak** [comment]
I'm inclined to get #304 merged for 0.3 so that generic-optics can get support for labels without our further intervention whenever @kcsongor resurfaces ;)

**Comment by phadej** [comment]
@adamgundry could you weight in?

**Comment by adamgundry** [comment]
Yes, let's go for #304 without further ado. As @arybczak says it is in an internal module so we can always back it out again if needed.

**Comment by phadej** [comment]
Then it makes us with #300 #304 and #306 waiting to be merged (I think they are all fine), after which I'll update #298 and merge it too.

**Comment by arybczak** [comment]
Please don't release yet (until tomorrow maybe), I have a small idea to explore.

**Comment by phadej** [comment]
The deadline was there to not linger the release any longer. I'd be less strict if there were `optics` release compatible with GHC-8.10, but there aren't. If you know whether you want something in by tomorrow, then it can get in. Otherwise whatever it is, it should wait.

**Comment by arybczak** [comment]
It's #307.

**Comment by adamgundry** [comment]
Resolved by #312.

**Comment by phadej** [comment]
@adamgundry thanks!
