### ISSUE TITLE
Config switch for TH generation of affine fields

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#318]
Consider this:

```haskell
data Human = Human { name :: String, pet :: Maybe Pet }
data Pet = Pet { name :: String, age :: Maybe Int }
```

Now if you have a human and you want to get age of its pet (which might be unknown), you need to use `preview (#pet % _Just % #age % _Just)`, which is quite annoying.

What if we introduced a config switch that would make TH generate `AffineTraversal` instead of `Lens` for fields of type `Maybe a`? Then `preview (#pet % #age)` would be enough.

**Comment by phadej** [comment]
What about `Option`, or `Either e` or other fields?

I don't like non-uniformity.

**Comment by arybczak** [comment]
`Option` is deprecated, `Either` has `Left`.

`Maybe` is somewhat canonical because of `afolding`.

**Comment by phadej** [comment]
@arybczak your call. I don't htink it's good idea, the `Maybe` will be even more special, and you won't be able to set the field to `Just x` or `Nothing`.

Let's see how hairy the patch will be.

**Comment by arybczak** [comment]
> you won't be able to set the field to Just x or Nothing.

Oops, you're right, I was thinking mostly in terms of getters :disappointed:  Oh well. I'll think about it.

**Comment by arybczak** [comment]
Closing as it seems like a bad idea in retrospect.
