### ISSUE TITLE
optics-core-0.3.0.1 and optics-th-0.3.0.1

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#329]
After #326 is merged I'd like to release optics-core-0.3.0.1 and optics-th-0.3.0.1 as since 0.3 was released we've got only a few documentation improvements and bug fixes.

Any objections?

**Comment by phadej** [comment]
The only change hoogle sees is 

```diff
@@@ Optics.Internal.Optic
--[getOptic] :: Optic (k :: OpticKind) (is :: IxList) s t a b -> forall p i. Profunctor p => Optic_ k p i (Curry is i) s t a b
+ getOptic :: Profunctor p => Optic k is s t a b -> Optic_ k p i (Curry is i) s t a b
```

so :+1: from me.

**Comment by arybczak** [comment]
https://hackage.haskell.org/package/optics-core-0.3.0.1
https://hackage.haskell.org/package/optics-th-0.3.0.1

:tada:
