### ISSUE TITLE
Fundep restrictions of LabelOptic can be lifted

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#364]
I just found out that all the fundep related restrictions of `LabelOptic` can be lifted.

```haskell
-- higher rank fields

data Rank2 = Rank2 { rank2 :: forall a. a -> a  }

instance
  ( LabelOptic "rank2" k Rank2 Rank2 x y
  , k ~ A_Getter
  , x ~ (a -> a)
  , y ~ (a -> a)
  ) => LabelOptic "rank2" k Rank2 Rank2 x y where
  labelOptic = to (\x -> rank2 x)

-- phantom types

data Phantom a = Phantom { phantom :: Int } deriving Show

instance
  ( LabelOptic "phantom" k (Phantom a) (Phantom b) x y
  , k ~ A_Lens
  , x ~ Int
  , y ~ Int
  ) => LabelOptic "phantom" k (Phantom a) (Phantom b) x y where
  labelOptic = lensVL $ \f (Phantom c) -> Phantom <$> f c

-- ambiguous type family application

type family Fam a
data TF a = TF { tf :: Fam a }

instance
  ( LabelOptic "tf" k (TF a) (TF b) x y
  , k ~ A_Lens
  , x ~ Fam a
  , y ~ Fam b
  ) => LabelOptic "tf" k (TF a) (TF b) x y where
  labelOptic = lensVL $ \f (TF tf) -> TF <$> f tf
```

Apparently including the instance head in the constraints satisfies GHC as it happily compiles and runs this code.

```haskell
λ> over #phantom (+1) (Phantom @Char 6) :: Phantom Bool
Phantom {phantom = 7}
λ> Rank2 id ^. #rank2 $ "Hi there"
"Hi there"
```

This is... unexpected.

**Comment by adamgundry** [comment]
Sorry for the delay, I've been on holiday and then trying to catch up.

I'm ~~terrified~~ amazed that this works. I haven't followed all the discussion arising from https://gitlab.haskell.org/ghc/ghc/-/issues/18759 but should we be worried that this trick will break in future GHC releases?

**Comment by arybczak** [comment]
It "almost always" works. GHC goes into a loop when trying to infer types of local bindings with `MonomorphismRestriction` enabled (see https://gitlab.haskell.org/ghc/ghc/-/issues/18759#note_308140 for an example).

I created a [GHC proposal](https://github.com/ghc-proposals/ghc-proposals/pull/374) that hopefully is accepted and makes this predictable.
