### ISSUE TITLE
Tests fail with 9.0.1 because of unsafeEqualityProof

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#396]
15 of tests fail with GHC 9.0.1, mostly because of unsafeEqualityProof, e.g.

```haskell
        tests/Optics/Tests/Utils.hs:56:
        tests/Optics/Tests/Labels/TH.hs:61:20: label5lhs ==- label5rhs failed:            
            LHS:                                                                          
                label5lhs = label5lhs_szze `cast` <Co:31>                                 
                                                                                          
                label5lhs_szze                                                            
                  = \ @a @b s name_ age_ fishName_ pets_ ->                               
                      case unsafeEqualityProof of { UnsafeRefl co2 ->
                      case s of { Human x1_af3x x2_af3y x3_af3z x4_af3A ->
                      (Human
                         name_
                         age_
                         (case x3_af3z of {
                            GoldFish x1_aeS2 -> GoldFish fishName_;
                            Herring x1_aeS4 -> Herring fishName_
                          })
                         pets_)
                      `cast` <Co:4>
                      }
                      }
                
            RHS:
                label5rhs
                  = \ @a @b s name_ age_ fishName_ pets_ ->
                      case s of { Human ds_dpF7 ds_dpF8 ds_dpF9 ds_dpFa ->
                      Human
                        name_
                        age_
                        (case ds_dpF9 of {
                           GoldFish ds_dpEY -> GoldFish fishName_;
                           Herring ds_dpEZ -> Herring fishName_
                         })
                        pets_
                      }
```

Does anyone know why are these in a release? I know they used to show in GHC compiled from git in the past, but they didn't in releases.

**Comment by phadej** [comment]
The `Unsafe.Coerce` module seem to have changed a lot in `base-4.15` https://downloads.haskell.org/ghc/9.0.1/docs/html/libraries/base-4.15.0.0/src/Unsafe-Coerce.html#unsafeCoerce

**Comment by arybczak** [comment]
I see.

The description on `UnsafeEquality` says:

> -- | This type is treated magically within GHC. **Any pattern match of the
> -- form @case unsafeEqualityProof of UnsafeRefl -> body@ gets transformed just into @body@.**
> -- This is ill-typed, but the transformation takes place after type-checking is
> -- complete. It is used to implement 'unsafeCoerce'. You probably don't want to
> -- use 'UnsafeRefl' in an expression, but you might conceivably want to pattern-match
> -- on it. Use 'unsafeEqualityProof' to create one of these.``

The fragment I highlighted doesn't seem to happen though.

**Comment by arybczak** [comment]
Related: https://gitlab.haskell.org/ghc/ghc/-/issues/19324

Looks like we need to kill the `unsafeCoerce` after all if we want to have working inspection tests.
