### ISSUE TITLE
Template Haskell optics

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#4]
I suppose we have to support TH generation of optics for record fields.

**Comment by adamgundry** [comment]
@arybczak since you expressed an interest in this, I'm assigning to you for now. Feel free to change your mind though. :wink:

**Comment by kosmikus** [comment]
Isn't this done? See also #63.

**Comment by phadej** [comment]
@kosmikus not done, there's optics to work with TH; but not TH to generate optics :)

**Comment by kosmikus** [comment]
Ok then. I seem to remember @arybczak said he'd done this. But perhaps it's just work in progress?

**Comment by arybczak** [comment]
I just ported a few required modules so far, it's still WIP.

**Comment by arybczak** [comment]
Done via #83.
