### ISSUE TITLE
Make optics-operators package

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#40]
The `lens` operator vocabulary is very rich (e.g. https://twitter.com/puffnfresh/status/1079935253261762561)

So we could move current `Optics.Operators` to be `Optics.Operators.Simple` and make a `Optics.Operators` replicating the `lens`.

Or we can have all in `optics-core` too if it will still depend on `mtl` (it's bundled since GHC-8.4, so it's *almost* a boot lib)

**Comment by arybczak** [comment]
I'd argue that it's too rich and I personally wouldn't want to replicate it. I think what we have in Optics.Operators is probably (almost) enough.

**Comment by adamgundry** [comment]
Indeed, there's an interesting tension here between replicating `lens` as-is and choosing to be more selective. I also prefer a small set of operators, usually avoiding the monadic ones.

If we do want to offer more, I'd be inclined not to have a separate `optics-operators` package but to either add `mtl` as a dependency on `optics-core` or just make them part of an `optics` batteries-included package.

**Comment by kosmikus** [comment]
I must say I'm rather fond of making it at separate package, if we provide these at all. I think the use of all these operators should mostly be discouraged. If a batteries-included `optics` package, there's little discouragement. On the other hand, having them may still be useful to allow easier porting for code that happens to use a lot of these.

**Comment by phadej** [comment]
I added `Optics.Operators.State` already, and so far i''m happy with the ones there

**Comment by arybczak** [comment]
It looks like no-one is sad about having a restricted set of operators, closing for now.
