### ISSUE TITLE
Update template-haskell-optics to support template-haskell-2.17.0.0 and 2.18.0.0

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#404]
@patrickt I don't suppose you'd be willing to contribute a patch?

**Comment by phadej** [comment]
There is template-haskell-2.18.0.0 too.

**Comment by patrickt** [comment]
This is waiting for https://github.com/well-typed/generics-sop/pull/147

**Comment by arybczak** [comment]
Ping :) It's no longer waiting.

**Comment by patrickt** [comment]
@arybczak It looks like Oleg may have beaten me to this? The bounds on template-haskell are now `template-haskell       >= 2.12      && <2.18`.

**Comment by arybczak** [comment]
Sadly the bounds are wrong, the package doesn't actually compile with GHC 9.0.2. It would be also good to update it to work with GHC 9.2. It's most likely as easy as porting changes to the relevant modules in `lens`.

**Comment by patrickt** [comment]
Ahh, gotcha. Added to my to-do list.
