### ISSUE TITLE
Make an Optic interface a little more abstract (hide indexed implementation details)

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#41]
Problem: Talk.pdf says "This just works, because our Lens type isn’t polymorphic"

But it's not true. The true 'Lens' type in current @optics@ is

    forall i. Lens i s t a b

i.e. we __have__ leave it free. Not good.
(We can set it to () or Void, to put into container,
 but then we cannot compose with those optics)

Also the double indices __leak__ the implementation details. Not good either.

Solition: We can cure this, with some additional hackery.
And we can make CheckIndices less hacky, as it would only match on type level list!
I only comment the parts which are changed.

The idea is to use 

    newtype Optic (k :: OptikKind) (is :: [Type) s t a b
        Optic (forall p i. Constraints k p => p i a b -> p (Curry is i) s t)

abstract interface. I.e. move the first (of double indices) to be inside the
Optic.

Note: The implementation is still a compromise.
- A_Setter has always empty index list
- An_IxSettter has always non empty index list
But we are forced to it this way so Constraints reduce properly.  i.e. we can
`sub` Setter into IxSetter, but it would be unusable (as it would have empty
index list.

We can use CheckIndices (and CheckNonIndices if we like) to get better errors.
I think latter is not needed as library doesn't give means to construct
non-indexed optic with non-empty index-list.

More elegantly we'd only have `A_Setter` and differentiate
between indexed and non-indexed variants based on index-list.
But then the type-checker will fight back.

- Making Constraints (k :: OpticKind) (is :: [*]) p breaks `Is` implementation:
  in implies `is` is rigid, so type-family cannot match on it (or we need more
  proofs)

- Using `Constraints An_Traversal p = IxTraversing p`
  but then e.g. `over` would need to be implemented using `IxFunArrow`,
  e.g. passing some dummy index value. Not good.

The full gist is in https://gist.github.com/phadej/0a1b1aa95f102a78d4e26b82f45da903

@arybczak What do you think about this?

**Comment by arybczak** [comment]
Do you think it can be made to play nicely with stuff in #44? Also, why can't we precompose icompose* functions with this version?

**Comment by adamgundry** [comment]
Interesting. I rather like the fact that indexing becomes actually orthogonal to optic kind, and that we reduce the number of points in the lattice.

Are there any performance concerns with this approach? I guess that using an indexed optic as if it were unindexed could end up passing around unused indices, but we can still have an explicit conversion from indexed to unindexed, and invoke `CheckNonIndexed` if we want to force its use. Though I do wonder if we should offer variants of e.g. `over` that just work for both indexed and unindexed?

**Comment by phadej** [comment]
About performance:
- very quick `inspection-testing` suggests that we don't pay for "bigger" constraint.
- going from indexed to non-indexed indeed passes unused indices around. Thus we don't offer "indexed by default optics"
- about indexing-polymorphic `over`. Not sure you really need it. `over` vs. `iover` provides a bit little redundancy to catch mistakes.
    - Let's not export this variants by default, if we decide to do them

**Comment by phadej** [comment]
Third variant: https://gist.github.com/phadej/888057607584ed94d78b950a4dd94ae0

**Comment by arybczak** [comment]
Hmm, so basically we'd then get rid of An_IxTraversal, An_IxFold and An_IxSetter and distinguish between regular/indexed versions by looking at the list that represents indices, right?

I like the idea of merging Ix and non-Ix classes (we can then just keep regular names), then I suppose we can get indexed lens, getter (and more if we want / it's feasible) nearly for free if we choose to?

That sounds promising 👍

**Comment by phadej** [comment]
I tried to combine classes, and run into a problem with reversing `ixcontramap`.
Solution isn't that bad, and actually expected.

https://gist.github.com/phadej/f4e5cc20bc6d91c62250d392be6c676e

**Comment by kosmikus** [comment]
I can't say I understand this fully yet, but it generally sounds like an interesting line of development to me.
