### ISSUE TITLE
optics-sop defines `record`; should it  rather be `product` or `nproduct`

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#42]
It (could) use `IsProductType` alias `generics-sop` defines...

**Comment by phadej** [comment]
@kosmikus Do you have an opinion

**Comment by phadej** [comment]
argh. `product` clashes with `Prelude` name.

**Comment by kosmikus** [comment]
Then I'd probably go for `productRep` instead, because it is like `rep`, but specialised to a product type.
