### ISSUE TITLE
Misleading error message from JoinKinds 

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#423]
With 0.4 and current HEAD:
```
ghci> :t castOptic @A_Setter @A_Setter (traversed % _1)

<interactive>:1:42: error:
    • A_Traversal cannot be composed with A_Lens
    • In the third argument of ‘castOptic’, namely ‘(traversed % _1)’
      In the expression: castOptic @A_Setter @A_Setter (traversed % _1)
```

Oops! I think what is going on here is that we get a constraint `JoinKinds A_Traversal A_Lens A_Setter` which of course does not match the instance `JoinKinds A_Traversal A_Lens A_Traversal`, so the catch-all error instance fires. Ideally we would have two different errors, one for "this composition doesn't make sense" and another for "this composition makes sense, but produces an optic of a different kind to that expected by the context".

**Comment by dminuoso** [comment]
I managed to provoke this version of an error:

```
• An_AffineTraversal cannot be composed with An_AffineTraversal
```

Even more confusing to the unsuspecting.

**Comment by arybczak** [comment]
Uh. @dminuoso do you have a reproducer? If not, can you please check if the situation is improved by #439?

**Comment by dminuoso** [comment]
This trivially reproduces the diagnostic:
```
united % united :: AffineFold () ()
```

With #439 I get:

```
<interactive>:2:2: error:
    • Couldn't match type ‘An_AffineFold’ with ‘A_Lens’
        arising from a use of ‘%’
    • In the expression: united % united :: AffineFold () ()
      In an equation for ‘it’: it = united % united :: AffineFold () ()
```

which is a huge improvement. :)
