### ISSUE TITLE
transformers-0.6

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#431]
- `optics-core` compiles fine. 
- `optics-extra` will need a patch as `ListT` and `ErrorT` are gone, but  this is blocked because there is no `transformers-0.6`-compatible `mtl` release

Should we make a revision for `optics-core` while waiting for new releases of `mtl`, `primitive` (we depend on it via `vector`)

**Comment by arybczak** [comment]
> Should we make a revision for optics-core

I don't see why not :+1:

**Comment by phadej** [comment]
See https://github.com/well-typed/optics/pull/454

**Comment by phadej** [comment]
I made revisions for `optics-core` and `optics-th`. But as mentioned in #454, `optics-extra` will need a proper release. (And then we can make revision for `optics`).

**Comment by adamgundry** [comment]
`optics-extra-0.4.2` released (and `optics-0.4.2` since it re-exports the `optics-extra` API).
