### ISSUE TITLE
Numeric state operators

### ISSUE THREAD

**Issue by georgefst** [well-typed/optics#433]
When using `lens` I've always made a lot of use of `+=`, `-=`, `*=` [(docs)](https://hackage.haskell.org/package/lens-5.0.1/docs/Control-Lens-Operators.html#v:-43--61-).

Could these perhaps be added to `optics-extra`? I know there's a bit of an issue about where to draw the line. But those three at least are pretty neat.

e.g.:
```hs
(+=) :: (Is k A_Setter, MonadState s m, Num a) => Optic' k is s a -> a -> m ()
l += x = l %= (+ x)
```

**Comment by arybczak** [comment]
I (and presumably other authors unless something changed since the last time we discussed this) am not a fan of these in particular because as you demonstrated, doing what you want is trivial with `%=` or `%~`.

**Comment by georgefst** [comment]
Fair enough. Next time I end up defining them I'll consider publishing a tiny library.

**Comment by qwbarch** [comment]
For anyone looking for these in the future: https://github.com/qwbarch/optics-operators
Will be adding other lens operators in here later on
