### ISSUE TITLE
Plated

### ISSUE THREAD

**Issue by Boarders** [well-typed/optics#435]
Are there any plans to add something similar to plated from lenses? In particular, I find the `template` function very handy for generating Traversals for free and wonder what the equivalent is with this library?

**Comment by fishtreesugar** [comment]
#379

**Comment by arybczak** [comment]
There's #379 for all the utilities, but if you only need generic traversal like `template`, there's [gplate](https://hackage.haskell.org/package/optics-core-0.4/docs/Optics-Generic.html#v:gplate).

**Comment by arybczak** [comment]
#379 got merged.
