### ISSUE TITLE
Rename *WithIndex to Ix*

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#48]
This is good for consistency, and as a bonus avoids clashes with `lens`.

I'll do this when there are no much other stuff in flight.

**Comment by adamgundry** [comment]
I'm not sure about this. Morally the classes are *the same* as the ones in `lens`, aren't they? (Although it seems `lens` includes optics in the class dictionaries, presumably for performance reasons.) So in some sense our versions are really replacements for the `lens` ones and using the same names might make their relationship clearer.

**Comment by phadej** [comment]
A compromise is to have `FunctorWithIndex`, `FoldableWithIndex`, `TraversableWithIndex`, but name profunctors with `Ix` prefix.

Or then all `*WithIndex`  (we have `IxProfunctor` now).

**Comment by arybczak** [comment]
Having internal classes with Ix prefix sounds fine to me, public ones can stay as-is so that people used to lens naming aren't confused.

**Comment by arybczak** [comment]
Resolved via #49.
