### ISSUE TITLE
Allow dependencies bundled with GHC-9.8

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#498]
new bytestring, text are disallowed in at least `optics-extra`.

EDIT: adding a GHC-9.8 CI job would be great as well.

**Comment by phadej** [comment]
ping

**Comment by ysangkok** [comment]
@adamgundry Would you prefer a PR for this, or would you prefer that people just wait for Well-Typed to do the work?

**Comment by adamgundry** [comment]
PRs are always welcome. :-)
