### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#5]
This should explain the motivation behind `optics`, basic usage and the differences from `lens`.

**Comment by arybczak** [comment]
Perhaps we should move stuff that currently sits in optics/src/Optics.hs into README?

Then it's displayed on both github and hackage.

**Comment by adamgundry** [comment]
Good plan. I'm still planning to do a pass over the documentation at some point, but time is ever a problem...

**Comment by phadej** [comment]
Note: `optics/src/Optics.hs` has haddock tests

**Comment by arybczak** [comment]
See #121. Do we want to have it? Perhaps not into optics-core, but in general.

Btw, the implementation of labels is nice in a sense that when https://ghc.haskell.org/trac/ghc/ticket/16232 is done, we can replace generic-lens code for type-preserving lenses with the HasField stuff to save compilation time in the majority of cases.

**Comment by adamgundry** [comment]
I'm now inclined to make the README relatively minimal, with some brief motivation and a link to the Haddocks on Hackage, rather than duplicating content. But it still needs to be written.
