### ISSUE TITLE
Rename `ViewableOptic` to simply `View` / consider its validity

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#57]

**Comment by kosmikus** [comment]
Is there any true benefit to having the `View(ableOptic)` generalisation over just having the `view1`, `view01`, and `viewN` functions to use which are more precise?

**Comment by arybczak** [comment]
API compatibility with `lens` and `^.` that "just works".

**Comment by kosmikus** [comment]
I'm not yet convinced this is an advantage in this case.

**Comment by arybczak** [comment]
FWIW I'm pretty sure that if we don't have `.^` (which is most likely (one of) the most used operators in lens) the stream of complaints will be endless.

**Comment by kosmikus** [comment]
Oh, I think we should have `^.`, but I think it should be equivalent to `flip view1`.

**Comment by arybczak** [comment]
I have an idea.

What about making view for Fold and Traversal be toListOf?

That's consistent with other implementations of view - Lens/Getter give you `r`, Prism/AffineTraversal/AffineFold give you `Maybe r`, it's only logical that Traversal/Fold give you `[r]`. 

I think one of the first mistakes people make with `lens` is that they try to view a traversal or fold and expect a list, but instead they get that confusing error message about `no Monoid instance for` (or completely unexpected result if the return type happens be a Monoid). That change will make it work as expected.

**Comment by arybczak** [comment]
Another possibility is to scrap ViewableOptic class altogether and:
- rename `view1` to `view`
- rename `view01` to `preview` and remove original `preview` that acts on folds. We can later add `firstOf` that does the same thing (but more efficiently, according to lens documentation).
- rename `viewN` to `foldOf`

**Comment by arybczak** [comment]
I'm pretty convinced that the above is the move to go for, except we should also keep ViewableOptic class with current polymorphic `view` (after renaming it to something like `gview`) as it's needed for things like `passthrough` and `use`.

**Comment by arybczak** [comment]
> Another possibility is to scrap ViewableOptic class altogether and:
> 
>     * rename `view1` to `view`
> 
>     * rename `view01` to `preview` and remove original `preview` that acts on folds. We can later add `firstOf` that does the same thing (but more efficiently, according to lens documentation).
> 
>     * rename `viewN` to `foldOf`

> I'm pretty convinced that the above is the move to go for, except we should also keep ViewableOptic class with current polymorphic `view` (after renaming it to something like `gview`) as it's needed for things like `passthrough` and `use`.

Both things were done.
