### ISSUE TITLE
Ticked vs unticked optics tags

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#58]
Let's choose one. If we change representation of indices to a type level list, clients of the library will need DataKinds anyway, so we can remove type aliases then.

**Comment by adamgundry** [comment]
My vote is unticked. The ticks are just an ugly hack GHC uses for disambiguation, and should be avoided as much as possible IMHO.

Regarding the indices I wonder if we could do something like (following #41):
```hs
type IxList = [Type]
type NoIx = ('[] :: IxList)
type WithIx i = ('[i] :: IxList)

type Setter = Optic A_Setter NoIx
type IxSetter i = Optic A_Setter (WithIx i)
```
so users don't have to think about `DataKinds` at least for non-indexed uses?

**Comment by phadej** [comment]
Resolved as in *unicked* until GHC provides `data type` i.e. `kind`
