### ISSUE TITLE
Move TH derivation to its own package

### ISSUE THREAD

**Issue by kosmikus** [well-typed/optics#63]
I'd much prefer if `optics-core` would not depend on TH. Just like `optics-sop` is separate, I think `optics-th` should be separate as well.

For SOP, we've done a complicated reorganisation recently to split off TH-independent parts into `sop-core`. I think not having a necessary TH dependency is a big advantage.

**Comment by phadej** [comment]
To be clear, providing TH-code doesn't require `{-# LANGUAGE TemplateHaskell #-}` anywhere; only `build-depends: template-haskell`.

**Comment by phadej** [comment]
`template-haskell` dependent code is moved to `optics-th`

**Comment by arybczak** [comment]
Done via #83.
