### ISSUE TITLE
Provide `from` or don't.

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#70]
> Perhaps we should expose from in Optics.Iso as a specialisation of re, just for consistency with lens?

https://github.com/well-typed/optics/pull/43#discussion_r247121380

Options:

```
-- 1. alias
from = re

-- 2. restricted alias
from = re :: Iso s t a b -> Iso b a t s -- (working with Equality too)

-- 3. no alias
```

My preference is 3, then 1, then 2.

**Comment by arybczak** [comment]
I'd like to ideally avoid the alias.

**Comment by adamgundry** [comment]
I don't really object to 3. Perhaps let's just make a "how to port code from `lens`" document somewhere that includes "replace `from` with `re`"?

**Comment by phadej** [comment]
@adamgundry I think for now it would be enough to mention technical differences in documentation; it's not yet too long section to justify separate document.

**Comment by adamgundry** [comment]
We now mention the absence of `from` in the docs, so let's close this.
