### ISSUE TITLE
Another package named e.g. `optics-extra`

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#81]
I think there needs to be another package between `optics-core` and `optics-th` that contains stuff that TH uses, but also pulls in a couple more dependencies for completeness of instances.

E.g. TH needs `Data.Data.Optics` (#80), but it:
- has nothing to do with TH
- requires `unordered-containers`

TH generation also needs
- `Control.Lens.At` - Not yet ported, I think can be worked around.
- `Control.Lens.Wrapped` - This is used for generation of `Wrapped` instances for newtypes. We can skip it for now. The code is mostly trivial, but it has tons of dependencies.
- `Data.Tuple.Optics` - We can provide local versions of these if we really want.

Currently `Optics.Each` and indexed optics are missing instances for `unordered-containers` (and lesser extent `text`, `bytestring`, `vector`). I think it would be good to fit these into `optics-extra` (along with `Data.Data.Optics`) and add missing instances.

Or somewhere.

**Comment by phadej** [comment]
Why optics TH-generation needs so much stuff?

**Comment by arybczak** [comment]
Because the code makes active use of the lens library.

**Comment by arybczak** [comment]
I think the dependency graph should be similar to this:

![deps](https://user-images.githubusercontent.com/387658/51286265-896e5480-19f2-11e9-961e-24a8985eaf6b.png)

Characterization of packages:
- `optics-core` - core definitions and lightweight helpers only. Dependencies: `base`.
- `optics-indexed` - provides `itraversed`, `ifolded`, `imapped` along with associated `{Functor,Foldable,Traversable}WithIndex` classes. Dependencies: `array`, `containers`, `unordered-containers`, `vector`, `transformers` to get all of the core instances in place.
- `optics` - provides all of the other, not-so-lightweight helpers such as `At`, `Each`, `Data.Tuple.Optics` etc. Dependencies: same as `optics-indexed` + `bytestring` and `text`.

Perhaps we want a package such as `optics-everything` that pulls in all of these, but that makes little sense to me. There is no point for `optics` to pull `optics-sop` if one doesn't use `generics-sop`. Same for `optics-th` and `generic-optics`, not only are they completely optional, they are somewhat mutually exclusive.

To be fair it's not clear to me yet where optics-th lies because of `Control.Lens.Wrapped`. Maybe it needs to depend of `optics`.

**Comment by phadej** [comment]
I see. Indeed our definition of indexed optics doesn't rely on `FunctorWithIndex` classes. That's good observation. :+1: to `optics-indexed`, less orphans.

To my understanding we want `optics` to be a package "which is enough for most people".
It might re-export `optics-sop` and `optics-th`.

Recall, `generic-optics` provides `IsLabel` instance, as well it `generic-lens` provides positions which removes code from `Data.Tuple.Optics` defaults. Maybe there are other places where `generic-lens` definitions are useful. This are good argument to have `generic-optics` functionality exported through `optics`.

To add, we need a place to put conversions from (and to?) `p a (f b) -> p s (f f)` (i.e. prisms), that needs to depend on `profunctors` (`optics-conversions` ?). This conversions would be needed for `generic-optics`.

`optics-everything` :-1:

I'm not sure about `_Wrapped`, do we need it at all. Either you write explicit `Iso`, or use `Coercible`.

```haskell
calaf :: forall f g a b. (Functor f, Functor g, Coercible a b)
      => (a -> b) -> (f b -> g b) -> f a -> g a
calaf _ = auf coerced
```

**Comment by arybczak** [comment]
> To my understanding we want `optics` to be a package "which is enough for most people".
> It might re-export `optics-sop` and `optics-th`.

In that case we need to have `optics-extra` and then `optics` would be just a meta package that pulls and re-exports these.

@adamgundry @kosmikus thoughts?

> I'm not sure about _Wrapped, do we need it at all. Either you write explicit Iso, or use Coercible.

Yeah, it looks like Wrapped predates Coercible by quite a lot. Perhaps it's best to not include it, at least for now.

**Comment by adamgundry** [comment]
> In that case we need to have `optics-extra` and then `optics` would be just a meta package that pulls and re-exports these.

Yes, that sounds like the right approach to me. The `optics` package should be batteries-included (e.g. with TH/generics for optic generation), so it's enough on its own in the common case, and I would expect it to simply be re-exporting modules from other packages. I can see that we're likely to need `optics-extra`. It's not obvious to me whether `optics-indexed` and `optics-extra` are worth separating?

The idea is that users who really care about minimal deps (i.e. libraries) can depend on the individual packages they need, while those who just want to try the library or use it in applications can use `optics` without any fuss.
